apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-pvc
  namespace: {{ .Values.pipelinesNamespace }}
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines