apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.pipelinesNamespace }}
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pod-security.kubernetes.io/enforce: restricted
